
version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:8
    # working_directory: /tmp

jobs:
  build:
    executor: my-executor
    steps:
      - run: sudo apt install rsync
  deploy:
    executor: my-executor
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello circle" # run the `echo` command
      - run:
          name: Print the current date and time
          command: date
      - run:
          name: See if rsync is available
          command: rsync

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
